### PR TITLE
Fix test_cgcheck_20

### PR DESCRIPTION
**Pull request by kunom**

### CODE REVIEW

**Comment by slozier** [comment]
Do you think it would be a lot of work to get the tests to ignore spacing differences instead of having it need to match exactly?

**Comment by kunom** [comment]
It depends on how tolerant you want to be. Just ignoring empty lines and indentation differences should not be too difficult, as long as you accept that multiline strings are handled in the same way.

If, on the other hand, you also want to accept braces placed on new lines and many other things performed by VS auto formatting, then this might become quite hairy.

If the first strategy is sufficient to you, then I can create a PR for that.

**Comment by kunom** [comment]
See #1373 as an alternative to this PR.

**Comment by slide** [comment]
I merged #1373, should this be closed out?

**Comment by kunom** [comment]
Yes. This has been obsoleted by #1373.

**Pull request closed without merging**
