### PR TITLE
[WIP] Remove IronRuby from repository

### PR DESCRIPTION
**Pull request by simplicbe**

### CODE REVIEW

**Comment by slide** [comment]
@simplicbe You want to rebase this against ipy-maint-2.7?

**Comment by simplicbe** [comment]
@slide done.

**Comment by slide** [comment]
I really don't like that all the merges are in this one. Rebasing on master shouldn't have all of the merges that have been done since you submitted this. In other words, this PR needs to be cleaned up and only have the commits that make the changes you want.

**Comment by simplicbe** [comment]
To be honest, I don't really get what you mean. I've rebased on the newest commit. What should I do?

**Comment by slozier** [comment]
@simplicbe I think he means something like `git checkout no_ruby` followed by `git rebase ipy-2.7-maint`...

**Comment by slide** [comment]
Closing and reopening to get a build

**Pull request closed without merging**
