### PR TITLE
Get pointer from _CFuncPtr in GetPointer

### PR DESCRIPTION
**Pull request by simplicbe**
This PR should solve #951. It would be nice if someone could add a test-case, because I've never work with this `_CFuncPtr` before.

### CODE REVIEW

**Comment by slide** [comment]
Is there not something in the ctypes tests that cover this already?

**Comment by simplicbe** [comment]
I could not find anything. I'll try to write my own test case.

**Comment by slide** [comment]
Closing and reopening to get AppVeyor build

**Comment by slozier** [comment]
I think `modules_misc_ipy` should already run `ctypes_test.py`. So maybe add a note to remove `test_ctypes_ipy` from `IronPython.tests` once `modules_misc_ipy` is fixed?

Edit: `modules_misc_ipy` is now fixed.

**Comment by slide** [comment]
Closing and reopening to get a build.

**Comment by slide** [comment]
Your commits should never include another PR. This can't be merged right now.

**Comment by slide** [comment]
Superseded by #1431

**Pull request closed without merging**
