### PR TITLE
Precheck .Overloads parameter count

### PR DESCRIPTION
**Pull request by simplicbe**
Check whether theire is a method, which except a given amount of overloads. Previously wrong exceptions were returned, at first caused by the:

    PerfTrack.NoteEvent(PerfTrack.Categories.BindingTarget, "BuiltinFunction " + Value.Targets.Count + ", " + Value.Targets[0].GetParameters().Length);

Because `Value.Targets` does not contains any values if no match was found, later by this issue: #832

Should be fixed with a simple precheck:

overloads_checks

Maybe throwing a simple `System.Exception` is not the best choice in this place, any suggestions would be appreciated.

Test-Code:

```
from System import Math, Double
Math.Sqrt.Overloads[Double, Double](24)
```
Thanks!

### CODE REVIEW

**Comment by jdhardy** [comment]
I think a better fix is at L62 of the same file (L80 with your changes). It should read:

    if(newTargets.Length == 0) { ...

instead. Since `targets` cannot be null, or it will NPE well before that, the exception is dead code, which makes me think it's a typo.

**Comment by simplicbe** [comment]
Good point, changed that so now i just proof whether it's empty or not, and than call `ThrowOverloadException`. I think it is important that this line `_function.OverloadDictionary[tl] = bf = new BuiltinFunction(_function.Name, newTargets, Function.DeclaringType, _function.FunctionType);` will only be executed, if `newTargets.Length` is greater than `0`. Hope thats correct.

**Comment by slide** [comment]
The formatting changes in this make it difficult to actually see what all the changes are. Please make sure to retain the formatting of the file when making PR's.

**Comment by simplicbe** [comment]
Done

**Pull request merged**
