### PR TITLE
Adding implementation of C# based IP "compiler" based on IKVM

### PR DESCRIPTION
**Pull request by slide**
This is a C# port of pyc.py that adds some requested features like native resources. This version is based on IKVM.Reflection, which allows for more features and options to be used.

### CODE REVIEW

**Comment by slide** [comment]
Partially addresses https://github.com/IronLanguages/main/issues/991

**Comment by rassilon** [comment]
Wouldn't you also need to add the 3rd party license info in the appropriate places?

**Comment by slide** [comment]
I must not have pushed that file update. I'll add that to the branch.

**Comment by slide** [comment]
Any other comments on this, or can I merge it in?

**Comment by jdhardy** [comment]
LGTM. A README in the project folder with some documentation (command line usages for common scenarios, mainly) would be nice.

**Comment by slide** [comment]
Good call, I'll add that before merging.

**Comment by rassilon** [comment]
Don't forget to update the license info the IronPython.wxs installs if you want to add this new coolness to the WiX based installer of course. :smile:

**Comment by slide** [comment]
@rassilon I haven't looked at adding it to the WiX stuff yet. I'll do that in a separate PR.

**Pull request merged**
