### PR TITLE
Add travis.yml for Travis testing

### PR DESCRIPTION
**Pull request by Samureus**
It seems to be working (kind of?), see https://travis-ci.org/Samureus/main

### CODE REVIEW

**Review by slide — COMMENTED** [review]
You can use make test-ironpython here

**Comment by slide** [comment]
@moto-timo this looks like it might duplicate your PR?

**Comment by Samureus** [comment]
@slide sorry do you mean [make test-ipy](https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Makefile#L27)? I can try to match https://github.com/IronLanguages/ironpython3/pull/87/files with nunit, I just assumed that since the Makefile is newer than https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Solutions/IronPython.sln, it was the preferred method.

**Comment by Samureus** [comment]
@slide Ok now the fun begins --> https://travis-ci.org/IronLanguages/main/builds/175543852

**Comment by slide** [comment]
We definitely know there are test failures on mono and osx. Definitely fun :-)

**Pull request closed without merging**
