### PR TITLE
Fix two XML document parsing error. Add a work around for a tokenizer runtime exception.

### PR DESCRIPTION
**Pull request by Erguotou**

### CODE REVIEW

**Comment by jdhardy** [comment]
Does _position < _start indicate a logic error? Should it throw an exception instead of silently fixing it up?

**Comment by Erguotou** [comment]
I think it's a bug in the parser, but I can't find it. It did trigger exceptions from multiple places because token length is now negative. But users of IronPython.dll don't know how to handle the exceptions. For example, in SharpDevelop, it just goes to the unhandled exception function and pop up the report to SD dialog.

**Comment by jdhardy** [comment]
Do you have an example that triggers this scenario?

**Comment by Erguotou** [comment]
I do. Unfortunately I cannot share it because it contains our trade secrets. It's a large file, more than 1000 lines. I cannot reproduce it with a small file.

**Comment by jdhardy** [comment]
And the error occurs while parsing the large file? I'm assuming the issue
is that there is a syntax error in the large file and it confused the
parser to the point where it got in to a bad state.

I'm concerned that just setting the position if it's wrong will hide the
error and cause something else to break later on in the compilation
process. I would rather it catch the syntax error earlier and report a
better error.

You could try commenting out code until the file compiles without errors,
even if it doesn't run. That should at least isolate the error and help
produce a test case.

**Comment by Erguotou** [comment]
I think your assumption is right. 

It gets really annoying when you are editing a file and it suddenly pops up the Report to SD dialog and when you click on Continue, it pops up again. That's why I want to hide it in release build but leave the Debug.Assert in CheckInvariants(), and hope someone else encounter the same error and can find out the true cause. 

Looking at the code, I think it makes sense when you move _start, we adjust _position if it's before _start, because we just discarded the token that _position was at.

**Comment by paweljasinski** [comment]
any chance to anonimize the data which triggers the problem?

**Comment by Erguotou** [comment]
Sorry, no. Obfuscation doesn't really work for python. I understand this is not a fix, and the bug doesn't affect 99.9% of the users. So I am going to close it. 

Thanks for looking at it.

**Pull request closed without merging**
