### PR TITLE
Fix #1261

### LINKED ISSUE #1261: site.getsitepackages() returns wrong path for Linux
When running with Mono under Linux, the `site.getsitepackages()` method returns wrong path that doesn't exist.

My IronPython installation is under /usr/lib/ipy folder, and here is the result:

```
>>> import site
>>> site.getsitepackages()
['/usr/lib/ipy/lib/python2.7/site-packages', '/usr/lib/ipy/lib/site-python']
```

A simple workaround in site.py (L300) could fix this:

```
        if sys.platform in ('os2emx', 'riscos', 'cli'):
            sitepackages.append(os.path.join(prefix, "Lib", "site-packages"))
```

```
>>> site.getsitepackages()
['/usr/lib/ipy/Lib/site-packages']
```

### PR DESCRIPTION
**Pull request by slide**
Add cli in check for setting up prefix/Lib/site-packages

### CODE REVIEW

**Comment by simplicbe** [comment]
I'm currently not sure if there is a place where we keep changes like this in mind. We may should mark them with a label?

**Comment by slide** [comment]
@simplicbe  You mean for changes to things in the stdlib?

**Comment by simplicbe** [comment]
Exactly

**Comment by simplicbe** [comment]
Another option would be creating a wiki article for it.

**Pull request merged**
