### PR TITLE
Fix MetaPythonType.MetaGetBinderHelper.AddMetaGetAttribute()

### LINKED ISSUE #1269: FinishCondition not called before GetMetaObject
I see the exception in the title. It comes and goes depending on various changes in the Python sources, so it is not easily possible to provide a concise example. It happens under both Mono and .net.

Is this something that could be triggered from userspace? If so, what might I be doing wrong? If not, is there much chance of it getting fixed without an example? Anything I can try to help diagnose the bug, please let me know. Many thanks.

### PR DESCRIPTION
**Pull request by kunom**
This fixes #1269.

### CODE REVIEW

**Comment by slide** [comment]
Is there a possibility of adding a test to go along with this?

**Comment by kunom** [comment]
@slide There actually is a new test. I extended _test_metaclass.py_.

**Comment by slide** [comment]
Another problem of me looking at it on my phone, sorry.

**Comment by slide** [comment]
Closing and reopening to get the appveyor build.

**Pull request merged**
