### PR TITLE
Support wildcards in TestRunner /test: and /category: options

### PR DESCRIPTION
**Pull request by kunom**
With this patch, it becomes possible to issue `test-ipy.cmd /category:Languages\IronPython\IronPython\2.X*` (note the trailing asterisk).

### CODE REVIEW

**Comment by slide** [comment]
:+1:

**Comment by slozier** [comment]
`make test` seems to be stopping prematurely since this got pulled in...

**Comment by kunom** [comment]
It is a bit unclear about what issue you do observe, but there certainly is one difference in behavior that I missed: Category names have been tested for ".StartsWith()", now for exact match. The result is that only one category is executed instead of 16.

 I will deliver a fix for that.

As a short-term workaround, you can add an asterisk (`*`) to the appropriate line in `make.cmd`.

**Comment by slozier** [comment]
Thanks for the workaround, adding `*` to `make.cmd` gives the same behavior as before.

**Pull request merged**
