### PR TITLE
test fix #1284

### LINKED ISSUE #1284: Inverse hyperbolic sinus in math module returns nan for all values < -1
When using the asinh function from the math module, it returns nan for any value lesser than -1. 
it seems that the function tries to return a complex number, although the implementation is different from the cmath module (see attached text file).

[Document.txt](https://github.com/IronLanguages/main/files/197324/Document.txt)

Can anyone shade some light on this ?

Edit : 

Reading the code in the attached document, the flaw is in
`if (Math.Abs(v0) > 1.0) {
                return Math.Log(v0) + Math.Log(1.0 + MathUtils.Hypot(1.0, 1.0 / v0));}`

If v0 < -1.0, abs(v0)>1.0 and the function tries to return log(v0) with v0 negative, hence the bug.
math.sign method could be used to fix this : 

`if (Math.Abs(v0) > 1.0) {
                return Math.Sign(v0)*(Math.Log(Math.Abs(v0)) + Math.Log(1.0 + MathUtils.Hypot(1.0, 1.0 / v0)));}
`

### PR DESCRIPTION
**Pull request by jagaudin**
testing values of asinh with precision 1e-12

### CODE REVIEW

**Comment by slide** [comment]
Close and reopen to build against merged fix

**Comment by slide** [comment]
Hmmm, looks like your new test is failing even with the fix merged in

**Comment by jagaudin** [comment]
Is it an issue related to precision? I tried these values in a Python console on Linux and it was working but didn't build as I only have a Windows machine at work. Do you have a traceback?

**Comment by jagaudin** [comment]
I found the traceback. There was a missing minus sign in the last test, apologies. This should be fixed now.

**Comment by slide** [comment]
Thanks!

**Pull request merged**
