### PR TITLE
Fix #963: Fix IronPython memory leaks when creating multiple engines

### LINKED ISSUE #963: Memory Leak
IronPython seems to leak memory in some conditions.  

The attached test case demonstrates the following cases:  
- using Python.SetTrace(engine, delegate) leaks about 165k per script invocation.   
- importing the warning module from the hosting environment leaks about 1.4 M per script run.   
- importing the os module from the script also leaks about 1.4M per script.   
- Doing both imorts also leaks about 1.4M per script(!).   
- Combining all three of the above leads to an OutOfMemory Exception after about 331 cycles, boiling down to a leak of ~5MB per script run!   
- Doing none of the above (only print) apparently creates a leak-free program.   

I attached the test program. For the test runs above, I compiled it for .NET
4.0 and target "x86", as our production app also runs in that environment
(.NET 4.0 and 32-bit only). Execution was on Win7 64 Bit. All windows updates
installed.
## Work Item Details

**Original CodePlex Issue:**    [Issue 31764](http://ironpython.codeplex.com/workitem/31764)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Nov 17, 2011 at 7:10 AM
**Reported by:**    MarkusSchaber
**Updated on:** Oct 9 at 12:07 PM
**Updated by:** hfoffani
#### Plaintext Attachments

[CodePlex Issue #31764 Plain Text Attachments](https://gist.github.com/aa9fc514992d571ba095)
#### Binary Attachments

[IronPythonLeakTest.7z](http://ironpython.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=ironpython&WorkItemId=31764&FileAttachmentId=12239)[Src.zip](http://ironpython.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=ironpython&WorkItemId=31764&FileAttachmentId=13582)

### PR DESCRIPTION
**Pull request by jdhardy**
IronPython held references to various things in static fields. This eliminates the ones that are causing problems and preventing large object graphs from being freed. Particularly problematic was a static field keeping all `PythonType` wrappers of .NET types around, which transitively held a reference to a PythonContext, which held references to just about everything else in an engine. The solution is to keep the .NET types attached to the context so that it all becomes collectible at the same time.

### CODE REVIEW

**Comment by rassilon** [comment]
Glad you were able to find some culprits in the memory retention hunt!

Thanks,
Bill

**Comment by slide** [comment]
Nice! Do you have any numbers on this pre/post fix?

**Comment by jdhardy** [comment]
Based on the test case in #963, there's a pretty big difference in memory usage:

**Before (7395 MB)**
before

**After (17MB)**
after

**Comment by slide** [comment]
This is fantastic...I just feel bad that two modules I implemented had a hand in the problem. Are you waiting for review to merge because it LGTM.

**Comment by keertheee** [comment]
I face the memory leak issue in WPF/C# when I am using the IronPython DLLs to create script engine and scope. Is there a fix for this in WPF/C#?

**Comment by RamzaGarland360** [comment]
I have an application (external) that calls a new application. This application makes use of the Microsoft ConsoleHost and the IronPython 2.7.5 tool for C#. The issue is after we exit the IronPython sessions, all appears to close and collect, but when running Redgate ANTS, there are thousands of instances of PythonAST's and NameExpressions being held in memory.  Wondering if this fix will fix that issue as well.. Shouldn't they just disperse?

**Pull request merged**
