### PR TITLE
Limit max recursion depth by default.

### PR DESCRIPTION
**Pull request by kunom**
Related to IronLanguages/main#1192.

### CODE REVIEW

**Comment by jdhardy** [comment]
Unfortunately the RecursionLimit is basically ignored. You would also need to track every python stack frame entry/exit and break when the limit is hit. It's probably possible but I'm not sure what the performance hit might be.

**Comment by DinoV** [comment]
The reason why this is disabled by default is due to performance issues and there'll be a significant hit to function call performance from enabling this by default.  I don't think the limit is ignored though currently, we should do the proper enforcement every time a function is called, and someone hitting the issue here can always run with -X:RecursionLimit set

**Comment by kunom** [comment]
jdhardy, I am sorry but I need some more time to be able to follow your comment. At least in my tests with `hasattr`, setting a recursion limit worked.

DinoV, can you elaborate a bit more on what the exact significant performance issues are with enforcing the recursion limit? Is it the counter management in `PythonFunction.AddRecursionDepth()`? From a naive standpoint, enforcing the recursion limit is not more than incrementing, decrementing and comparing an integer.

Regarding IronLanguages/main#1192, I don't see an other way to achieve CPython compatiblity since `StackOverflowException`s are normally uncatchable since .NET 2.0. (In fatch, there is already a catch-all handler in `PythonOps.HasAttr()`).

**Comment by slide** [comment]
If you would like to recreate this PR, please do so under IronLanguages/ironpython2

**Pull request closed without merging**
