### PR TITLE
fix #1168 on 'l == r' try __rop_ before __op__ when r is subclass of l

### LINKED ISSUE #1168: `__eq__` of OrderedDict subclasses does not have precedence when comparing with OrderedDicts
First of all, is this the correct place to submit IronPython bugs or should I still use the tracker at http://ironpython.codeplex.com/? There aforementioned page has a note that source is here on GitHub but doesn't tell anything about issue tracker.

---

Running this code on CPython succeeds but with IronPython the second assert fails:

``` python
from collections import OrderedDict

class Example(OrderedDict):

    def __eq__(self, other):
        return True

e = Example()
o = OrderedDict(a=1)

assert e == o, 'e != o'
assert o == e, 'o != e'
```

Because `Example` is a subclass of `OrderedDict`, its `__eq__` should be used in both of the above comparisons.

Interestingly this version with `int` works correctly:

``` python
class Example(int):

    def __eq__(self, other):
        return True

e = Example()
o = 42

assert e == o, 'e != o'
assert o == e, 'o != e'
```

### PR DESCRIPTION
**Pull request by jagt**
Hi IronPython maintainers.

I've been using IronPython and now trying to hack on it. This is my first attempt :)

However there're some questions:
1. Which branch are you currently working on? I assume it's `ipy-2.7-maint`.
2. I noticed that tests related to this particular issue is disabled. What should I do to add some tests for this?
3. I've tried to run the tests on my machine and seems there's many failing cases. Is it always like this or am I doing something wrong?

Thanks.

### CODE REVIEW

**Comment by paweljasinski** [comment]
> Which branch are you currently working on? I assume it's ipy-2.7-maint.

ipy-2.7-maint is the right branch

> I noticed that tests related to this particular issue is disabled. What should I do to add some tests for this?

Can you name the test file, test case. Testing is in fuzzy state, but we are always happy to get more of it in shape.

> I've tried to run the tests on my machine and seems there's many failing cases. Is it always like this or am I doing something wrong?

There are legitimate tests which are failing, at the same time you may have not everything configured right. In the first case I usually compare before and after (there should be no new tests which are failing).

**Comment by jagt** [comment]
@paweljasinski Thanks for your reply.

> Can you name the test file, test case. Testing is in fuzzy state, but we are always happy to get more of it in shape.

I believe it's the `Languages\IronPython\IronPython\2.X\compat\compare` category.

**Comment by paweljasinski** [comment]
on the master there is a comment:

the missing part _runip_sbs.bat

**Comment by jagt** [comment]
I can hardly find any hint on how to find the `_runip_sbs.bat`... Any idea on this?

**Comment by jdhardy** [comment]
The SBS (side by side) tests are from when it was an MS project. I don't
think they've ever worked with the public code.

**Comment by paweljasinski** [comment]
I managed to get sbs tests going. Details in https://github.com/IronLanguages/main/pull/1175

**Comment by jagt** [comment]
@paweljasinski Thanks! I'll try these out.

**Comment by paweljasinski** [comment]
Since sbs works now you have 2 choices. 
1. add a new test case to test_class.py which exercise exactly the problem.
2. add a test to sbs which exposes discrepancy between cpython and ironpython
The 1st is probably easier.
Since the sbs tests are live now, they should be passing with your fix. 
And BTW, thanks for motivating us to get sbs going, I found a regression in one of formatting fixes.

**Comment by jagt** [comment]
@paweljasinski Thanks for the hints. I won't have access to my pc for a while, I'll be finishing up the tests later.

**Comment by jdhardy** [comment]
@jagt: any chance you've had a chance to finish up the tests for this?

**Comment by jagt** [comment]
@jdhardy believe it or not I still haven't access to my own PC.... I'll get this done when I've got my computer, maybe next month. Really sorry for this.

**Comment by jdhardy** [comment]
No worries. There aren't any real plans for 2.7.6 release yet.

**Comment by slide** [comment]
Any chance this can be ready to go sometime soon? We're planning on releasing more often, so this could get into a release if all the items above are addressed.

**Comment by jagt** [comment]
@slide I really forgot about this one. Will try to get this addressed over the weekend.

**Comment by slide** [comment]
I ran the test suite with this change in place and it causes failure in other tests.

**Comment by slide** [comment]
If you would like to recreate this PR, please do so under IronLanguages/ironpython2

**Pull request closed without merging**
