### PR TITLE
Partial fix for #917

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by slide** [comment]
:+1:

**Comment by slozier** [comment]
I'm not sure how I can unload the DLLs added with AddReference so I can delete them. Any ideas?

**Comment by slide** [comment]
I don't think you can, but each test should be run under it's own process, so the test could log a list of files to a file and then the wrapper scripts could look for that file and delete the files from that log. Kind of hacky though.

**Review by simplicbe — APPROVED** [review]
LGTM

**Comment by slozier** [comment]
Looks like there are a bunch of other temporary files that end up in the temp folder so I updated the tests to put the generated DLLs there instead.

**Pull request merged**
