### PR TITLE
Fix #923

### LINKED ISSUE #923: IronPython 2.7Beta2: re.sub method does not implement flags argument (that exists in CPython 2.7.1)
re.sub method does not implement flags argument in IronPython 2.7 Beta 2.  
flags argument is present in CPython 2.7.1 re.sub method ( [
http://docs.python.org/library/re.html
](http://docs.python.org/library/re.html) ).  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 30206](http://ironpython.codeplex.com/workitem/30206)
**Status:**	Active
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Feb 19, 2011 at 6:35 PM
**Reported by:**	iustinian
**Updated on:**	Oct 9, 2013 at 7:46 PM
**Updated by:**	Krubos

### PR DESCRIPTION
**Pull request by slozier**
... also cleanup overloads.

### CODE REVIEW

**Comment by slide** [comment]
test_re is currently disabled, does it pass now by chance?

**Comment by slozier** [comment]
No, I looked at it and we're not even close to passing (even after I disabled all the tests which are specific to the CPython implementation).

**Comment by slide** [comment]
Are there tests specific to these changes?

**Comment by slozier** [comment]
Added some tests for sub/subn with the flags parameter. The rest of the changes are already covered by the tests (`modules_io_related_ipy`).

**Pull request merged**
